shopSize: 3
refreshPrice: 100
shopTitle: ${player}'s Rand Shop
buttons:
  0:
    ==: Button
    commands:
      - server| say button server command test for ${player}!
      - say button player command test for ${player}!
    icon:
      type: STONE
      amount: 1
  4:
    ==: Button
    commands:
      - server| say button server command test for ${player}!
      - say button player command test for ${player}!
    icon:
      type: MAP
      amount: 5
  8:
    ==: Button
    commands:
      - server| say button server command test for ${player}!
      - say button player command test for ${player}!
    icon:
      type: RED_ROSE
      amount: 9
