name: RandShop
version: ${version}
author: Himmelt
main: org.soraworld.randshop.RandShop
depend:
  - PlayerPoints
description: RandShop Plugin.
permissions:
  randshop.admin:
    default: op
commands:
  randshop:
    usage: /randshop [reload]
    aliases:
      - rs
      - shop
      - rshop
    permission-message: You need permission <randshop.admin> to execute this command.
    description: randshop commands.
  addgood:
    usage: /addgood <name> <price> <rate>
    aliases:
      - agood
    permission: randshop.admin
    permission-message: You need permission <randshop.admin> to execute this command.
  setbutton:
    usage: /setbutton <index>
    aliases:
      - sbutton
    permission: randshop.admin
    permission-message: You need permission <randshop.admin> to execute this command.